import type { Customer, Product, Warehouse, Order, ProductStock } from '@/types/order' // Assuming these types are declared in a separate file

export const ORDER_STATUSES = ['Draft', 'Dikonfirmasi Sales', 'Diproses Gudang', 'Siap Kirim', 'Dalam Pengiriman', 'Selesai', 'Dibatalkan'] as const;

export const ORDER_TYPES = ['Sewa', 'Beli'] as const;

export const UNITS = ['btl', 'pcs', 'unit', 'lot'] as const;

// Mock data
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 1,
    customer_name: 'Budi Santoso',
    company_name: 'PT. Maju Bersama Logistik',
    phone: '08123456789',
    email: 'budi@majubersama.com',
    address: 'Jl. Merdeka No. 10, Surabaya, Jawa Timur',
  },
  {
    id: 2,
    customer_name: 'Siti Rahayu',
    company_name: 'CV. Berkah Jaya',
    phone: '08234567890',
    email: 'siti@berkahjaya.com',
    address: 'Jl. Sudirman No. 25, Jakarta Pusat',
  },
  {
    id: 3,
    customer_name: 'Ahmad Wijaya',
    company_name: 'PT. Teknik Industri',
    phone: '08345678901',
    email: 'ahmad@teknikindustri.com',
    address: 'Jl. Gatot Subroto No. 15, Bandung',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Tabung Oksigen 40m³ Baja Tekanan Tinggi',
    sku: 'O2-40M3-Baja',
    description: 'Tabung oksigen medis dan industri',
    category: 'Gas Medis',
  },
  {
    id: 2,
    name: 'Tabung Nitrogen 30m³ Industri',
    sku: 'N2-30M3-Industri',
    description: 'Tabung nitrogen untuk keperluan industri',
    category: 'Gas Industri',
  },
  {
    id: 3,
    name: 'Tabung Argon 25m³ Welding',
    sku: 'AR-25M3-Welding',
    description: 'Tabung argon untuk pengelasan',
    category: 'Gas Welding',
  },
  {
    id: 4,
    name: 'Tabung CO2 20m³ Food Grade',
    sku: 'CO2-20M3-Food',
    description: 'Tabung CO2 untuk industri makanan',
    category: 'Gas Food',
  },
  {
    id: 5,
    name: 'Tabung Helium 15m³ Balon',
    sku: 'HE-15M3-Balon',
    description: 'Tabung helium untuk balon',
    category: 'Gas Khusus',
  },
  {
    id: 6,
    name: 'Tabung Asetilena 50m³ Gas Industri Besar',
    sku: 'C2H2-50M3-Besar',
    description: 'Tabung asetilena untuk industri besar',
    category: 'Gas Industri',
  },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: 1,
    name: 'Gudang Pusat Jakarta',
    address: 'Jl. Raya Jakarta No. 100',
    manager_name: 'Pak Joko',
  },
  {
    id: 2,
    name: 'Gudang Surabaya',
    address: 'Jl. Industri Surabaya No. 50',
    manager_name: 'Bu Sari',
  },
  {
    id: 3,
    name: 'Gudang Bandung',
    address: 'Jl. Cihampelas No. 75',
    manager_name: 'Pak Dedi',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    order_number: 'O250708-00001',
    customer_id: 1,
    sales_user_id: 1,
    assigned_warehouse_id: 1,
    order_date: '2025-07-08T03:24:12.511Z',
    order_type: 'Sewa',
    status: 'Dikonfirmasi Sales',
    shipping_address: 'Jl. Merdeka No. 10, Surabaya, Jawa Timur',
    total_amount: null,
    notes_customer: 'Hubungi Bp. David di lokasi (08123456789) setibanya di sana.',
    notes_internal: null,
    createdAt: '2025-07-08T03:24:12.512Z',
    updatedAt: '2025-07-08T03:24:12.512Z',
    customer: {
      id: 1,
      customer_name: 'Budi Santoso',
      company_name: 'PT. Maju Bersama Logistik',
    },
    salesUser: {
      id: 1,
      name: 'Super Administrator',
    },
    items: [
      {
        id: 1,
        order_id: 1,
        product_id: 1,
        quantity: 3,
        unit: 'btl',
        unit_price: null,
        sub_total: null,
        is_rental: true,
        rental_start_date: null,
        rental_end_date: null,
        rental_duration_days: null,
        notes_petugas_gudang: null,
        createdAt: '2025-07-08T03:24:12.754Z',
        updatedAt: '2025-07-08T03:24:12.754Z',
        product: {
          id: 1,
          name: 'Tabung Oksigen 40m³ Baja Tekanan Tinggi',
          sku: 'O2-40M3-Baja',
        },
      },
      {
        id: 2,
        order_id: 1,
        product_id: 6,
        quantity: 2,
        unit: 'btl',
        unit_price: null,
        sub_total: null,
        is_rental: true,
        rental_start_date: null,
        rental_end_date: null,
        rental_duration_days: null,
        notes_petugas_gudang: null,
        createdAt: '2025-07-08T03:24:12.983Z',
        updatedAt: '2025-07-08T03:24:12.983Z',
        product: {
          id: 6,
          name: 'Tabung Asetilena 50m³ Gas Industri Besar',
          sku: 'C2H2-50M3-Besar',
        },
      },
    ],
  },
  {
    id: 2,
    order_number: 'O250708-00002',
    customer_id: 2,
    sales_user_id: 1,
    assigned_warehouse_id: 2,
    order_date: '2025-07-08T04:15:30.000Z',
    order_type: 'Beli',
    status: 'Diproses Gudang',
    shipping_address: 'Jl. Sudirman No. 25, Jakarta Pusat',
    total_amount: 2500000,
    notes_customer: 'Pengiriman sebelum jam 10 pagi',
    notes_internal: 'Prioritas tinggi',
    createdAt: '2025-07-08T04:15:30.000Z',
    updatedAt: '2025-07-08T04:15:30.000Z',
    customer: {
      id: 2,
      customer_name: 'Siti Rahayu',
      company_name: 'CV. Berkah Jaya',
    },
    salesUser: {
      id: 1,
      name: 'Super Administrator',
    },
    items: [
      {
        id: 3,
        order_id: 2,
        product_id: 2,
        quantity: 5,
        unit: 'btl',
        unit_price: 500000,
        sub_total: 2500000,
        is_rental: false,
        rental_start_date: null,
        rental_end_date: null,
        rental_duration_days: null,
        notes_petugas_gudang: null,
        createdAt: '2025-07-08T04:15:30.000Z',
        updatedAt: '2025-07-08T04:15:30.000Z',
        product: {
          id: 2,
          name: 'Tabung Nitrogen 30m³ Industri',
          sku: 'N2-30M3-Industri',
        },
      },
    ],
  },
  {
    id: 3,
    order_number: 'O250708-00003',
    customer_id: 3,
    sales_user_id: 1,
    assigned_warehouse_id: 1,
    order_date: '2025-07-08T05:30:45.000Z',
    order_type: 'Sewa',
    status: 'Siap Kirim',
    shipping_address: 'Jl. Gatot Subroto No. 15, Bandung',
    total_amount: null,
    notes_customer: null,
    notes_internal: 'Cek kondisi tabung sebelum kirim',
    createdAt: '2025-07-08T05:30:45.000Z',
    updatedAt: '2025-07-08T05:30:45.000Z',
    customer: {
      id: 3,
      customer_name: 'Ahmad Wijaya',
      company_name: 'PT. Teknik Industri',
    },
    salesUser: {
      id: 1,
      name: 'Super Administrator',
    },
    items: [
      {
        id: 4,
        order_id: 3,
        product_id: 3,
        quantity: 2,
        unit: 'btl',
        unit_price: null,
        sub_total: null,
        is_rental: true,
        rental_start_date: null,
        rental_end_date: null,
        rental_duration_days: null,
        notes_petugas_gudang: null,
        createdAt: '2025-07-08T05:30:45.000Z',
        updatedAt: '2025-07-08T05:30:45.000Z',
        product: {
          id: 3,
          name: 'Tabung Argon 25m³ Welding',
          sku: 'AR-25M3-Welding',
        },
      },
      {
        id: 5,
        order_id: 3,
        product_id: 4,
        quantity: 1,
        unit: 'btl',
        unit_price: null,
        sub_total: null,
        is_rental: true,
        rental_start_date: null,
        rental_end_date: null,
        rental_duration_days: null,
        notes_petugas_gudang: null,
        createdAt: '2025-07-08T05:30:45.000Z',
        updatedAt: '2025-07-08T05:30:45.000Z',
        product: {
          id: 4,
          name: 'Tabung CO2 20m³ Food Grade',
          sku: 'CO2-20M3-Food',
        },
      },
    ],
  },
];

export const MOCK_PRODUCT_STOCKS: Record<string, ProductStock> = {
  '1-1': { product_id: 1, warehouse_id: 1, available_stock: 25 },
  '1-2': { product_id: 1, warehouse_id: 2, available_stock: 15 },
  '1-3': { product_id: 1, warehouse_id: 3, available_stock: 8 },
  '2-1': { product_id: 2, warehouse_id: 1, available_stock: 30 },
  '2-2': { product_id: 2, warehouse_id: 2, available_stock: 20 },
  '2-3': { product_id: 2, warehouse_id: 3, available_stock: 12 },
  '3-1': { product_id: 3, warehouse_id: 1, available_stock: 18 },
  '3-2': { product_id: 3, warehouse_id: 2, available_stock: 22 },
  '3-3': { product_id: 3, warehouse_id: 3, available_stock: 10 },
  '4-1': { product_id: 4, warehouse_id: 1, available_stock: 35 },
  '4-2': { product_id: 4, warehouse_id: 2, available_stock: 28 },
  '4-3': { product_id: 4, warehouse_id: 3, available_stock: 15 },
  '5-1': { product_id: 5, warehouse_id: 1, available_stock: 12 },
  '5-2': { product_id: 5, warehouse_id: 2, available_stock: 8 },
  '5-3': { product_id: 5, warehouse_id: 3, available_stock: 5 },
  '6-1': { product_id: 6, warehouse_id: 1, available_stock: 20 },
  '6-2': { product_id: 6, warehouse_id: 2, available_stock: 15 },
  '6-3': { product_id: 6, warehouse_id: 3, available_stock: 10 },
};
